spring:
  jpa:
    hibernate:
      ddl-auto: create

    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
    defer-datasource-initialization: true

  datasource:
    username: root
    password: root
    url: jdbc:mariadb://i9a103.p.ssafy.io:3306/eyak
    driver-class-name: org.mariadb.jdbc.Driver

# resuorces/data.sql 을 애플리케이션 시작 시 자동 실행하도록 설정
  sql:
    init:
      mode: always

oauth2:
  provider:
    google:
      jwks: >
        {
          "keys": [
            {
              "n": "8KImylelEspnZ0X-ekZb9VPbUFhgB_yEPJuLKOhXOWJLVsU0hJP6B_mQOfVk0CHm66UsAhqV8qrINk-RXgwVaaFLMA827pbOOBhyvHsThcyo7AY5s6M7qbftFKKnkfVHO6c9TsQ9wpIfmhCVL3QgTlqlgFQWcNsY-qemSKpqvVi-We9I3kPvbTf0PKJ_rWA7GQQnU_GA5JRU46uvw4I1ODf0icNBHw7pWc7oTvmSl1G8OWABEyiFakcUG2Xd4qZnmWaKwLHBvifPuIyy2vK-yHH91mVZCuleVu53Vzj77RgUtF2EEuB-zizwC-fzaBmvnfx1kgQLsdK22J0Ivgu4Xw",
              "kty": "RSA",
              "use": "sig",
              "e": "AQAB",
              "kid": "fd48a75138d9d48f0aa635ef569c4e196f7ae8d6",
              "alg": "RS256"
            },
            {
              "kid": "911e39e27928ae9f1e9d1e21646de92d19351b44",
              "use": "sig",
              "kty": "RSA",
              "alg": "RS256",
              "e": "AQAB",
              "n": "4kGxcWQdTW43aszLmftsGswmwDDKdfcse-lKeT_zjZTB2KGw9E6LVY6IThJVxzYF6mcyU-Z5_jDAW_yi7D_gXep2rxchZvoFayXynbhxyfjK6RtJ6_k30j-WpsXCSAiNAkupYHUyDIBNocvUcrDJsC3U65l8jl1I3nW98X6d-IlAfEb2In2f0fR6d-_lhIQZjXLupjymJduPjjA8oXCUZ9bfAYPhGYj3ZELUHkAyDpZNrnSi8hFVMSUSnorAt9F7cKMUJDM4-Uopzaqcl_f-HxeKvxN7NjiLSiIYaHdgtTpCEuNvsch6q6JTsllJNr3c__BxrG4UMlJ3_KsPxbcvXw"
            }
          ]
        }

jwt:
  properties:
#    2시간
    access-token-expiration-time-in-milliseconds: 7200000
#    28일
    refresh-token-expiration-time-in-milliseconds: 2419200000

api-version: "/api/v1"

logging:
  level:
    now.eyak: debug

server:
  port: 8081
