spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    username: root
    password: root
    url: jdbc:mariadb://i9a103.p.ssafy.io:3306/eyak
    driver-class-name: org.mariadb.jdbc.Driver
server:
  port: 8081

