spring:
  jpa:
    hibernate:
      ddl-auto: none

    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
    defer-datasource-initialization: true

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:mariadb://i9a103.p.ssafy.io:3306/eyak
    driver-class-name: org.mariadb.jdbc.Driver

  sql:
    init:
      mode: never

  data:
    redis:
      host: i9a103.p.ssafy.io
      port: 6379
      password: ${REDIS_PASSWORD}

oauth2:
  provider:
    google:
      jwks: >
        {
          "keys": [
            {
              "kid": "7c9c78e3b00e1bb092d246c887b11220c87b7d20",
              "kty": "RSA",
              "alg": "RS256",
              "e": "AQAB",
              "use": "sig",
              "n": "pGMz603XOzO71r-LpW555Etbn2dXAtY4xToNE_Upr1EHxkHFnVnGPsbOeWzP8xU1IpAL56S3sTsbpCR_Ci_PYq8s4I3VWQM0u9w1D_e45S1KJTSex_aiMQ_cjTXb3Iekc00JIkMJhUaNnbsEt7PlOmnyFqvN-G3ZXVDfTuL2Wsn4tRMYf7YU3jgTVN2M_p7bcZYHhkEB-jzNeK7ub-6mOMkKdYWnk0jIoRfV63d32bub0pQpWv8sVmflgK2xKUSJVMZ7CM0FvJYJgF7y42KBPYc6Gm_UWE0uHazDgZgAvQQoNyEF_TRjVfGiihjPFYCPqvFcfLK4773JTD2fLZTgOQ"
            },
            {
              "use": "sig",
              "kid": "c3afe7a9bda46bae6ef97e46c95cda48912e5979",
              "e": "AQAB",
              "alg": "RS256",
              "n": "qxHzsqeQzXW-LT2Z-k30bJPhoMful1wUVPYUmukRR7qRnsC-7mQYaXkXaiuYcdlsZBS_AzfppQVIJ6GKncXQcZJ7-x-RwRm2exSdbmQ8xPJY1c1BLflc0Qa4fwGY_MjbR1kvlcx6etWhsnJqmivX9ALnCF5ZTR4ewC-BH7ZuilUYb6bCgG-zpSHNIQpgxO9gE8XoPBujGK9w6v_uzZb4rj2_8KWWT6RRBBQs1KDZmxzFkDcVOjgyTLmGPpHLQDF3R02DHzeaB84KB0QM-KyKIK1ejzCljdwCPAhNB9r14-01cUI1GUKuhv0tPgne3Je9qPIxl_g2FuZuqBnT1MPo9w",
              "kty": "RSA"
            }
          ]
        }

jwt:
  properties:
#    2시간
    access-token-expiration-time-in-milliseconds: 7200000
#    28일
    refresh-token-expiration-time-in-milliseconds: 2419200000

api-version: "/api/v1"

# Swagger springdoc-ui Configuration
springdoc:
  packages-to-scan: now.eyak
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui.html           # Swagger UI 경로 => localhost:8000/demo-ui.html
    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true

logging:
  level:
    root: debug

server:
  port: 8081
